// crypto.js
//
// Application-layer end-to-end encryption on top of WebRTC.
//
// Note on the security model, worth being precise about for a viva:
// WebRTC DataChannels are *already* mandatorily encrypted in transit via
// DTLS — the browser refuses to negotiate an unencrypted data channel. So
// technically, traffic between the two peers (and across a TURN relay, if
// one is in the path) is already protected.
//
// The AES-GCM layer added here is defense-in-depth and a deliberate design
// choice, not a gap-filler:
//   - The encryption key is generated by the initiating peer and handed to
//     the other peer only after the DataChannel is open, i.e. only after
//     the two browsers have a direct (or TURN-relayed) authenticated
//     channel — it never touches the signaling server.
//   - It means a compromised or malicious TURN relay — which by design can
//     see DTLS-terminated data channel bytes it is relaying — still only
//     ever sees ciphertext at the application layer.
//   - It keeps the encryption boundary in this app's own hands rather than
//     fully trusting the browser's WebRTC stack / TURN provider.

export async function generateKey() {
  return crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, true, ['encrypt', 'decrypt']);
}

export async function exportKey(key) {
  const raw = await crypto.subtle.exportKey('raw', key);
  return btoa(String.fromCharCode(...new Uint8Array(raw)));
}

export async function importKey(base64) {
  const raw = Uint8Array.from(atob(base64), (c) => c.charCodeAt(0));
  return crypto.subtle.importKey('raw', raw, { name: 'AES-GCM' }, true, ['encrypt', 'decrypt']);
}

/** Encrypts one chunk. A fresh random IV is generated per chunk and prepended to the output. */
export async function encryptChunk(key, data) {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ciphertext = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, data);
  const out = new Uint8Array(iv.byteLength + ciphertext.byteLength);
  out.set(iv, 0);
  out.set(new Uint8Array(ciphertext), iv.byteLength);
  return out.buffer;
}

export async function decryptChunk(key, data) {
  const buf = new Uint8Array(data);
  const iv = buf.slice(0, 12);
  const ciphertext = buf.slice(12);
  return crypto.subtle.decrypt({ name: 'AES-GCM', iv }, key, ciphertext);
}
